#!/bin/sh

server=$1

if [ X$server = X ]
then
  echo "usage: $0 server_address"
  exit 1
fi

for v in tls1 tls1_1 tls1_2; do
    for c in $(openssl ciphers 'ALL:eNULL' | tr ':' ' '); do 
        echo "HEAD /index.html" | openssl s_client -connect $server -cipher $c -$v > /dev/null 2>&1
        if [ $? -eq 1 ]
        then
          echo "NO: $v $c"
        else
          echo "YES: $v $c"
        fi 
    done
done
